goldfish_homepage:
    path:     /
    defaults: { _controller: DarkbluesunGoldfishBundle:Default:index }

_goldfish_projects:
    resource: "@DarkbluesunGoldfishBundle/Controller/ProjectController.php"
    type:     annotation

_goldfish_tasks:
    resource: "@DarkbluesunGoldfishBundle/Controller/TaskController.php"
    type:     annotation