app:
    path:     /app
    defaults: { _controller: DarkbluesunGoldfishBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: DarkbluesunGoldfishBundle:Default:login }

login_check:
    path:     /login_check

logout:
    path:     /logout

register:
    defaults: { _controller: DarkbluesunGoldfishBundle:Account:register }
    path:     /register

account_create:
    defaults: { _controller: DarkbluesunGoldfishBundle:Account:create }
    path:     /register/create

account_edit:
    defaults: { _controller: DarkbluesunGoldfishBundle:Account:edit }
    path:     /account/edit
account_update:
    defaults: { _controller: DarkbluesunGoldfishBundle:Account:update }
    methods:   PUT
    path:     /account/edit

_goldfish_clients:
    resource: "@DarkbluesunGoldfishBundle/Controller/API/ClientController.php"
    type:     rest
    prefix:   /api

_goldfish_projects:
    resource: "@DarkbluesunGoldfishBundle/Controller/API/ProjectController.php"
    type:     rest
    prefix:   /api

_goldfish_tasks:
    resource: "@DarkbluesunGoldfishBundle/Controller/API/TaskController.php"
    type:     rest
    prefix:   /api

_goldfish_users:
    resource: "@DarkbluesunGoldfishBundle/Controller/API/UserController.php"
    type:     rest
    prefix:   /api
