goldfish_homepage:
    path:     /
    defaults: { _controller: DarkbluesunGoldfishBundle:Default:index }

login:
    path:     /login
    defaults: { _controller: DarkbluesunGoldfishBundle:Default:login }

login_check:
    path:     /login_check

logout:
    path:     /logout

register:
    defaults: { _controller: DarkbluesunGoldfishBundle:Account:register }
    path:     /register

account_create:
    defaults: { _controller: DarkbluesunGoldfishBundle:Account:create }
    path:     /register/create

_goldfish_clients:
    resource: "@DarkbluesunGoldfishBundle/Controller/ClientController.php"
    type:     annotation

_goldfish_projects:
    resource: "@DarkbluesunGoldfishBundle/Controller/ProjectController.php"
    type:     annotation

_goldfish_tasks:
    resource: "@DarkbluesunGoldfishBundle/Controller/TaskController.php"
    type:     annotation